# https://taskfile.dev

version: "3"

dotenv:
  - ".env"

tasks:
  default:
    desc: "Gettings started"
    cmds:
      - task: service:up
      - task: install

  install:
    desc: "Install dependencies"
    cmds:
      - go mod download
      - go install github.com/cosmtrek/air@latest
      - go install github.com/a-h/templ/cmd/templ@latest

  service:up:
    desc: "Start services"
    cmd: docker-compose up -d

  service:down:
    desc: "Stop services"
    cmd: docker-compose down

  redis:cli:
    desc: "Connect to redis using command line interface"
    cmd: docker exec -it portfolio_redis redis-cli

  dev:
    desc: "Start development server"
    cmd: air

  lint:
    desc: "Run linter"
    cmd: golangci-lint run ./...

  build:
    desc: "Build binary"
    cmd: go build -o ./bin/{{.APP_NAME}} ./cmd/main.go
    requires:
      vars:
        - APP_NAME

  start:
    desc: "Start binary"
    cmd: ./bin/{{.APP_NAME}}
    requires:
      vars:
        - APP_NAME

  test:
    desc: "Run tests"
    cmds:
      - go test -v ./... -race -cover -timeout 30s -count 1 -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
