// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header><nav id=\"navbar\" class=\"container-fluid\"><ul><li><a href=\"/\" class=\"contrast\"><strong>Resume</strong></a></li></ul><ul><li><a href=\"/projects\" class=\"secondary outline\">Projects</a></li><li><a href=\"/blogs\" class=\"secondary outline\">Blogs</a></li><li><details class=\"dropdown\" role=\"list\" dir=\"rtl\"><summary aria-haspopup=\"listbox\" class=\"secondary\">Theme</summary><ul role=\"listbox\"><li><a href=\"./\" data-theme-switcher=\"auto\">Auto</a></li><li><a href=\"./\" data-theme-switcher=\"light\">Light</a></li><li><a href=\"./\" data-theme-switcher=\"dark\">Dark</a></li></ul></details></li></ul></nav></header><style>\n\t#navbar {\n\t\tview-transition-name: navbar;\n\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
